import {StyleSheet} from 'react-native';
export const style = StyleSheet.create({
  row: {
    flexDirection: 'row',
  },
  chatCard: {
    width: '75%',
    height: 153,
    borderRadius: 19,
    backgroundColor: '#1D1D27',
    marginTop: 33,
    marginLeft: 36,
  },
  chatTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#DDB937',
    marginTop: 19,
    marginLeft: 18,
  },
  chatHeading: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
    marginTop: 7,
    marginLeft: 18,
    lineHeight: 15.6,
  },
  profileImage: {
    position: 'absolute',
    top: 15,
    left: 54,
  },
  likeIconsView: {
    width: 30,
    height: 15,
    borderRadius: 26,
    backgroundColor: '#424247',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 28,
    left: '72%',
  },
  likeIconsText: {
    fontWeight: '400',
    fontSize: 6,
    color: '#DDB937',
  },
  postTime: {
    fontSize: 12,
    fontWeight: '400',
    color: '#505058',
    marginTop: 10,
    marginLeft: 51,
  },
  card2ProfileImage: {
    position: 'absolute',
    top: 13,
    left: 54,
  },
  likeIconsView2: {
    width: 30,
    height: 15,
    borderRadius: 26,
    backgroundColor: '#424247',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 25,
    left: '62%',
  },
  simleProfile: {
    marginTop: 13,
    marginLeft: 54,
  },
  simleProfileTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#DDB937',
    marginTop: 15,
    marginLeft: 11,
  },
  simleProfileHeading: {
    fontSize: 12,
    fontWeight: '400',
    color: '#FFFFFF',
    marginTop: 15,
    marginLeft: 6,
    lineHeight: 15.6,
  },
  simpleProfileRow: {
    flexDirection: 'row',
  },
  left: {
    marginLeft: 13,
  },
  height: {
    width: '65%',
    height: 119,
  },
});
